#add coordinates in on line 46
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
def format_coordinates(coord_list):
    coordinates = coord_list.split(" | ")
    formatted_xml = ""
    for coord_pair in coordinates:
        x, z = coord_pair.split(" / ")
        formatted_xml += f'<pos x="{x}" z="{z}" a="-1" />\n'
    return formatted_xml.strip()  # Remove trailing newline

def main():
    coordinates_input = "X / Z | X / Z"
    formatted_xml = format_coordinates(coordinates_input)
    
    print("\nFormatted coordinates in XML format:")
    print(formatted_xml)

if __name__ == "__main__":
    main()
